// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNMqLXkVoktMwH1xtudQ7MYerNLhikIM',
    appId: '1:958533272830:web:ee8a9e26e78e04732091af',
    messagingSenderId: '958533272830',
    projectId: 'registration-backend-9201c',
    authDomain: 'registration-backend-9201c.firebaseapp.com',
    storageBucket: 'registration-backend-9201c.firebasestorage.app',
    measurementId: 'G-2C0LDW62S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvsSqwl5cK_9IgvvwQ2deaIMluy3qAdLI',
    appId: '1:958533272830:android:58306b5d77c2772d2091af',
    messagingSenderId: '958533272830',
    projectId: 'registration-backend-9201c',
    storageBucket: 'registration-backend-9201c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMXi0Y9uHLCmUbu6woZjxey0gftVSDWY',
    appId: '1:958533272830:ios:dd3ec967936965ac2091af',
    messagingSenderId: '958533272830',
    projectId: 'registration-backend-9201c',
    storageBucket: 'registration-backend-9201c.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMXi0Y9uHLCmUbu6woZjxey0gftVSDWY',
    appId: '1:958533272830:ios:dd3ec967936965ac2091af',
    messagingSenderId: '958533272830',
    projectId: 'registration-backend-9201c',
    storageBucket: 'registration-backend-9201c.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNMqLXkVoktMwH1xtudQ7MYerNLhikIM',
    appId: '1:958533272830:web:8b5e957df9f0b75e2091af',
    messagingSenderId: '958533272830',
    projectId: 'registration-backend-9201c',
    authDomain: 'registration-backend-9201c.firebaseapp.com',
    storageBucket: 'registration-backend-9201c.firebasestorage.app',
    measurementId: 'G-292LHTPTGK',
  );
}
